- tests/executor.cpp
To try how this works. Based entirely on add test, but it seems to work.
> Added OR-test

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor.cpp
- tests/instruction.cpp
- Implemented sll, sllv, sra, srav, srl, srlv instructions.
- Added test cases. Note that sign extension of sra and srav are implementation dependent so additional testing might be needed for them.
> Added shift instructions.

- include/mips-emulator/executor.hpp
> Fixed formatting.

- include/mips-emulator/register_file.hpp
- tests/executor.cpp
- tests/register_file.cpp
Overengineered files and irrelevant to MIPS32
> Removed Templated register file

- include/mips-emulator/executor.hpp
- tests/executor.cpp
Added the slt and sltu instructions as well as some very basic tests for both.
> SLT and SLTU instructions

- include/mips-emulator/emulator.hpp
- include/mips-emulator/executor.hpp
- tests/executor.cpp
> Implement lb sb lw sw instructions.

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor.cpp
- tests/instruction.cpp
Added wsbh instruction and tests.
Some groundwork to deal with different special3 instructions since they have different layouts depending on the Func field.
Fixes #197.
> Implement wsbh instruction and tests.

- include/mips-emulator/instruction.hpp
tiny pr :) swapps j-type and i-type in get_type
closes #218
> fix get_type for i/j-type

- tests/instruction.cpp
tests for _get_type_ function for r/i/j-type instructions.
> get_type tests for r-,i- and j-types

- tests/executor.cpp
> fix store halfword test

- include/mips-emulator/executor.hpp
- include/mips-emulator/register_file.hpp
- tests/executor.cpp
- tests/register_file.cpp
- adds function uppdate_pc that increments and preformes delayed branching
- adds tests for update_pc
- updates branching instructions to use delayd branching
- updates tests to work for delayed branching
> Delay slot

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor.cpp
- tests/instruction.cpp
> Implement bitswap instruction and tests.

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor.cpp
more tests for load itype instrs.
closes #88 
closes #94  
closes #3
> lbu and lhu + more load tests

- include/mips-emulator/runtime_static_memory.hpp
Added a constructor to RuntimeStaticMemory which takes a vector.
> Added constructor to RuntimeStaticMemory

- tests/executor/itype.cpp
- tests/executor/rtype.cpp
Also made or-test a bit better.
closes #236
> Added tests for ad, sop32/33, n/xor, sub/addu, addiu

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor/rtype.cpp
Added clo, clz instructions and tests.
Closes #50.
Closes #51.
> Added clo, clz instructions

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/CMakeLists.txt
- tests/executor/itype.cpp
- tests/executor/regimm.cpp
- tests/instruction.cpp
Implementation of the branch instructions BLTZ, BGEZ, BGEZ and BLEZ that Love and I worked on this week. In order to process regimm-type instructions we decided to add a new instruction type the same way that it was added for special3-type instructions. A new executor testfile regimm.cpp was also added for regimm tests.
> Branch instr

- include/mips-emulator/memory.hpp
The *_no_mmio variants avoid reaching out to the MMIO handler on reads and stores wich avoids an extra branch.
> Added *_no_mmio variants of read and store

- tests/executor/regimm.cpp
get rid of most copy/paste code in branch tests-
> clean up regimm tests

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor/special3.cpp
- tests/instruction.cpp
> Added special3 ins and ext instructions.

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
Closes #106 #21 #25 #18 
I'm still a bit unsure about the sign extension on the type 2 instructions. Do we need to sign extend when we've already shifted by 16 bits?
Tests are also needed
> PC relative instructions

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor.cpp
- tests/executor/itype.cpp
- tests/instruction.cpp
> Compact branches

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- tests/executor/jtype.cpp
now with tests!
Closes #29 #28
> added bc and balc

- include/mips-emulator/executor.hpp
- include/mips-emulator/instruction.hpp
- include/mips-emulator/register_file.hpp
- tests/executor/rtype.cpp
- Adds a cause register and BadInstr (wherein the error code is stored) as well as a function for signaling exceptions. 
- Adds conditional trap instructions TEQ, TGE, TGEU, TLT, TLTU, TNE
> Exception support and Conditional Trap instructions
